### PR TITLE
Update for Matrix

### PR DESCRIPTION
**Pull request by drinfernoo**
This pull request should fix most issues that prevented the script from running on Matrix, as well as making it cross-compatible between Leia and Matrix.

I tried to catch any errors that arose in the process, but there may still be a few I missed, admittedly. Namely, there were a handful of method calls (like `xrange` and `reduce`) that seemed to either be incorrectly imported, or not cross-compatible between Python 2 and 3. I have also handled a couple Kodi API changes, like `xbmc.translatePath` and `xbmc.LOGNOTICE` being deprecated in Matrix.

I've tested this on Aura in Leia, and @SerpentDrago's version of AuraMOD in Matrix, and all of the effects appear to be working now.

### CODE REVIEW

**Comment by Goldenfreddy0703** [comment]
Yoooo i just wanna say, thank you so much for trying to make this script compatible with Matrix. Your the best and i hope this script gets merged soon.

**Comment by drinfernoo** [comment]
@BADMS Have you gotten a chance to review this?

**Comment by BADMS** [comment]
Ok here now, stick with me...

**Comment by drinfernoo** [comment]
Thanks for the merge 👍

**Pull request merged**
